name: Install Nix pinned

description: Install a pinned version of Nix.

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v27
      with:
        # Workaround https://github.com/nix-community/dream2nix/issues/1037
        install_url: "https://releases.nixos.org/nix/nix-2.18.5/install"
    - uses: DeterminateSystems/magic-nix-cache-action@main
