name: Test the main branch

on:
  push:
    branches: [main]

jobs:
  push-ruff-pinned:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          push-to-cachix: true
          paths-to-push: result
          # This is the repository secret, set by @ShamrockLee
          cachix-auth-token: ${{secrets.CACHIX_AUTH_TOKEN_RW}}
      - run: nix build --show-trace --print-out-paths --print-build-logs .#ruff_d2n

  nix-flake-check:
    if: ${{ always() }}
    needs: push-ruff-pinned
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
      - name: Test the Nix flake
        run: nix flake check --keep-going --show-trace --print-build-logs

  test-nix-infra-env:
    if: ${{ always() }}
    needs: push-ruff-pinned
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
      - name: Test the infra environment used by other GitHub workflows.
        run: nix develop -c echo infra development environment success
